# FIXME: These should line up with versions in Version.xcconfig
set(PURC_MAC_VERSION 0.0.1)
set(MACOSX_FRAMEWORK_BUNDLE_VERSION 0.0.1)

find_package(LibXml2 2.8.0)
find_package(LibXslt 1.1.7)
find_package(CURL 7.60.0)
find_package(OpenSSL 1.1.1)
find_package(SQLite3 3.10.0)
find_package(BISON 3.0 REQUIRED)
find_package(FLEX 2.6.4 REQUIRED)

PURC_OPTION_BEGIN()
# Private options shared with other PurC ports. Add options here only if
# we need a value different from the default defined in PurCFeatures.cmake.

PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_SOCKET_STREAM PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_XML PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_HTTP PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_LSQL PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_RSQL PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_HIBUS PUBLIC OFF)
PURC_OPTION_DEFAULT_PORT_VALUE(ENABLE_SSL PUBLIC OFF)

PURC_OPTION_END()

set(PurC_PKGCONFIG_FILE ${CMAKE_BINARY_DIR}/Source/PurC/purc.pc)

set(PurC_LIBRARY_TYPE SHARED)
set(PurCTestSupport_LIBRARY_TYPE SHARED)

