/**
 * @file multi.h
 * @author 
 * @date 2021/07/02
 * @brief The hearder file for multiple encoding.
 *
 * Copyright (C) 2021 FMSoft <https://www.fmsoft.cn>
 *
 * This file is a part of PurC (short for Purring Cat), an HVML interpreter.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/multi-byte.py"!
 * Do not change this file!
 */


#ifndef PCHTML_ENCODING_MULTI_H
#define PCHTML_ENCODING_MULTI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "config.h"
#include "html/encoding/base.h"

#include "html/core/shs.h"


#define PCHTML_ENCODING_MULTI_HASH_BIG5_SIZE 20172
#define PCHTML_ENCODING_MULTI_HASH_EUC_KR_SIZE 28041
#define PCHTML_ENCODING_MULTI_HASH_GB18030_SIZE 19950
#define PCHTML_ENCODING_MULTI_HASH_ISO_2022_JP_KATAKANA_SIZE 52
#define PCHTML_ENCODING_MULTI_HASH_JIS0208_SIZE 9253
#define PCHTML_ENCODING_MULTI_HASH_JIS0212_SIZE 6923


PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_big5[19782];
PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_euc_kr[23750];
PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_gb18030[23940];
PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_iso_2022_jp_katakana[63];
PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_jis0208[11104];
PCHTML_EXTERN const pchtml_encoding_multi_index_t pchtml_encoding_multi_index_jis0212[7211];

PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_big5[23033];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_euc_kr[30109];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_gb18030[23941];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_iso_2022_jp_katakana[72];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_jis0208[11349];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_multi_hash_jis0212[8552];


#ifdef __cplusplus
}       /* __cplusplus */
#endif

#endif  /* PCHTML_ENCODING_MULTI_H */
