/**
 * @file single.h
 * @author 
 * @date 2021/07/02
 * @brief The hearder file for encoding and decoding.
 *
 * Copyright (C) 2021 FMSoft <https://www.fmsoft.cn>
 *
 * This file is a part of PurC (short for Purring Cat), an HVML interpreter.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/single-byte.py"!
 * Do not change this file!
 */


#ifndef PCHTML_ENCODING_SINGLE_H
#define PCHTML_ENCODING_SINGLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "config.h"
#include "html/encoding/base.h"

#include "html/core/shs.h"


#define PCHTML_ENCODING_SINGLE_HASH_IBM866_SIZE 344
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_10_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_13_SIZE 345
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_14_SIZE 407
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_15_SIZE 344
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_16_SIZE 413
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_2_SIZE 368
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_3_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_4_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_5_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_6_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_7_SIZE 344
#define PCHTML_ENCODING_SINGLE_HASH_ISO_8859_8_SIZE 347
#define PCHTML_ENCODING_SINGLE_HASH_KOI8_R_SIZE 486
#define PCHTML_ENCODING_SINGLE_HASH_KOI8_U_SIZE 380
#define PCHTML_ENCODING_SINGLE_HASH_MACINTOSH_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1250_SIZE 432
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1251_SIZE 362
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1252_SIZE 373
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1253_SIZE 354
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1254_SIZE 354
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1255_SIZE 467
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1256_SIZE 343
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1257_SIZE 355
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_1258_SIZE 405
#define PCHTML_ENCODING_SINGLE_HASH_WINDOWS_874_SIZE 359
#define PCHTML_ENCODING_SINGLE_HASH_X_MAC_CYRILLIC_SIZE 373


PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_ibm866[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_10[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_13[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_14[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_15[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_16[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_2[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_3[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_4[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_5[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_6[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_7[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_iso_8859_8[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_koi8_r[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_koi8_u[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_macintosh[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1250[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1251[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1252[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1253[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1254[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1255[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1256[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1257[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_1258[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_windows_874[128];
PCHTML_EXTERN const pchtml_encoding_single_index_t pchtml_encoding_single_index_x_mac_cyrillic[128];

PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_ibm866[345];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_10[344];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_13[346];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_14[408];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_15[345];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_16[414];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_2[369];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_3[344];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_4[344];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_5[344];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_6[344];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_7[345];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_iso_8859_8[348];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_koi8_r[487];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_koi8_u[381];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_macintosh[351];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1250[433];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1251[363];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1252[374];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1253[355];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1254[355];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1255[468];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1256[357];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1257[356];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_1258[406];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_windows_874[360];
PCHTML_EXTERN const pchtml_shs_hash_t pchtml_encoding_single_hash_x_mac_cyrillic[374];


#ifdef __cplusplus
}       /* __cplusplus */
#endif

#endif  /* PCHTML_ENCODING_SINGLE_H */
