#!/bin/bash

bison -d mathlex.y
flex -o mathlex.lex.c mathlex.l
bison -d mathldlex.y
flex -o mathldlex.lex.c mathldlex.l
bison -d logicallex.y
flex -o logicallex.lex.c logicallex.l

cp mathlex.lex.* mathlex.tab.* mathldlex.lex.* mathldlex.tab.* logicallex.lex.* logicallex.tab.* ../../dvobjs/ 
