/*
 * This file is part of CSSEng
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2009 John-Mark Bell <jmb@netsurf-browser.org>
 */

#ifndef css_select_propset_h_
#define css_select_propset_h_

#include <string.h>

#include "csseng-computed.h"

#include "computed.h"
#include "select/autogenerated_propset.h"

#endif
