/**
 * @file attr_res.h
 * @author 
 * @date 2021/07/02
 * @brief The hearder file for resource of html tag attribution.
 *
 * Copyright (C) 2021 FMSoft <https://www.fmsoft.cn>
 *
 * This file is a part of PurC (short for Purring Cat), an HVML interpreter.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */


#ifndef PCEDOM_ATTR_RES_H
#define PCEDOM_ATTR_RES_H

#include "config.h"
#include "html/core/shs.h"

#include "private/edom/attr_const.h"


static const pcedom_attr_data_t pcedom_attr_res_data_default[PCEDOM_ATTR__LAST_ENTRY] = 
{
    {{.u.short_str = "#undef", .length = 6, .next = NULL},
     PCEDOM_ATTR__UNDEF, 1, true},
    {{.u.short_str = "alt", .length = 3, .next = NULL},
     PCEDOM_ATTR_ALT, 1, true},
    {{.u.short_str = "charser", .length = 7, .next = NULL},
     PCEDOM_ATTR_CHARSER, 1, true},
    {{.u.short_str = "checked", .length = 7, .next = NULL},
     PCEDOM_ATTR_CHECKED, 1, true},
    {{.u.short_str = "class", .length = 5, .next = NULL},
     PCEDOM_ATTR_CLASS, 1, true},
    {{.u.short_str = "color", .length = 5, .next = NULL},
     PCEDOM_ATTR_COLOR, 1, true},
    {{.u.short_str = "content", .length = 7, .next = NULL},
     PCEDOM_ATTR_CONTENT, 1, true},
    {{.u.short_str = "dir", .length = 3, .next = NULL},
     PCEDOM_ATTR_DIR, 1, true},
    {{.u.short_str = "disabled", .length = 8, .next = NULL},
     PCEDOM_ATTR_DISABLED, 1, true},
    {{.u.short_str = "face", .length = 4, .next = NULL},
     PCEDOM_ATTR_FACE, 1, true},
    {{.u.short_str = "for", .length = 3, .next = NULL},
     PCEDOM_ATTR_FOR, 1, true},
    {{.u.short_str = "height", .length = 6, .next = NULL},
     PCEDOM_ATTR_HEIGHT, 1, true},
    {{.u.short_str = "href", .length = 4, .next = NULL},
     PCEDOM_ATTR_HREF, 1, true},
    {{.u.short_str = "html", .length = 4, .next = NULL},
     PCEDOM_ATTR_HTML, 1, true},
    {{.u.short_str = "http-equiv", .length = 10, .next = NULL},
     PCEDOM_ATTR_HTTP_EQUIV, 1, true},
    {{.u.short_str = "id", .length = 2, .next = NULL},
     PCEDOM_ATTR_ID, 1, true},
    {{.u.short_str = "is", .length = 2, .next = NULL},
     PCEDOM_ATTR_IS, 1, true},
    {{.u.short_str = "maxlength", .length = 9, .next = NULL},
     PCEDOM_ATTR_MAXLENGTH, 1, true},
    {{.u.short_str = "pool", .length = 4, .next = NULL},
     PCEDOM_ATTR_POOL, 1, true},
    {{.u.short_str = "public", .length = 6, .next = NULL},
     PCEDOM_ATTR_PUBLIC, 1, true},
    {{.u.short_str = "scheme", .length = 6, .next = NULL},
     PCEDOM_ATTR_SCHEME, 1, true},
    {{.u.short_str = "size", .length = 4, .next = NULL},
     PCEDOM_ATTR_SIZE, 1, true},
    {{.u.short_str = "slot", .length = 4, .next = NULL},
     PCEDOM_ATTR_SLOT, 1, true},
    {{.u.short_str = "src", .length = 3, .next = NULL},
     PCEDOM_ATTR_SRC, 1, true},
    {{.u.short_str = "style", .length = 5, .next = NULL},
     PCEDOM_ATTR_STYLE, 1, true},
    {{.u.short_str = "system", .length = 6, .next = NULL},
     PCEDOM_ATTR_SYSTEM, 1, true},
    {{.u.short_str = "title", .length = 5, .next = NULL},
     PCEDOM_ATTR_TITLE, 1, true},
    {{.u.short_str = "type", .length = 4, .next = NULL},
     PCEDOM_ATTR_TYPE, 1, true},
    {{.u.short_str = "width", .length = 5, .next = NULL},
     PCEDOM_ATTR_WIDTH, 1, true}
};

static const pchtml_shs_entry_t pcedom_attr_res_shs_data[30] = 
{
    {NULL, NULL, 29, 0}, 
    {(char *)"maxlength", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_MAXLENGTH], 9, 0}, 
    {(char *)"disabled", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_DISABLED], 8, 1}, 
    {(char *)"type", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_TYPE], 4, 0}, 
    {(char *)"alt", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_ALT], 3, 0}, 
    {(char *)"slot", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_SLOT], 4, 3}, 
    {(char *)"title", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_TITLE], 5, 0}, 
    {(char *)"class", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_CLASS], 5, 11}, 
    {(char *)"color", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_COLOR], 5, 12}, 
    {(char *)"http-equiv", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_HTTP_EQUIV], 10, 0}, 
    {(char *)"id", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_ID], 2, 15}, 
    {(char *)"height", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_HEIGHT], 6, 0}, 
    {(char *)"content", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_CONTENT], 7, 0}, 
    {(char *)"html", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_HTML], 4, 0}, 
    {(char *)"dir", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_DIR], 3, 17}, 
    {(char *)"charser", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_CHARSER], 7, 0}, 
    {(char *)"src", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_SRC], 3, 0}, 
    {(char *)"width", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_WIDTH], 5, 0}, 
    {(char *)"for", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_FOR], 3, 0}, 
    {(char *)"href", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_HREF], 4, 26}, 
    {(char *)"style", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_STYLE], 5, 0}, 
    {(char *)"scheme", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_SCHEME], 6, 0}, 
    {(char *)"pool", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_POOL], 4, 0}, 
    {(char *)"face", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_FACE], 4, 0}, 
    {(char *)"checked", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_CHECKED], 7, 0}, 
    {(char *)"#undef", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR__UNDEF], 6, 28}, 
    {(char *)"size", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_SIZE], 4, 0}, 
    {(char *)"is", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_IS], 2, 0}, 
    {(char *)"public", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_PUBLIC], 6, 0}, 
    {(char *)"system", (void *) &pcedom_attr_res_data_default[PCEDOM_ATTR_SYSTEM], 6, 0}
};


#endif  /* PCEDOM_ATTR_RES_H */
