/*
 * @file tokenizer.c
 * @author Xue Shuming
 * @date 2022/02/08
 * @brief The implementation of hvml tokenizer.
 *
 * Copyright (C) 2021 FMSoft <https://www.fmsoft.cn>
 *
 * This file is a part of PurC (short for Purring Cat), an HVML interpreter.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

#include "config.h"

#include "tokenizer.h"

#include "private/instance.h"
#include "private/errors.h"
#include "private/debug.h"
#include "private/utils.h"
#include "private/dom.h"
#include "private/hvml.h"

#include "hvml-buffer.h"
#include "hvml-rwswrap.h"
#include "hvml-token.h"
#include "hvml-sbst.h"
#include "hvml-attr.h"
#include "hvml-tag.h"

#include <math.h>

#if HAVE(GLIB)
#include <gmodule.h>
#else
#include <stdlib.h>
#endif

#if 0
PCHVML_NEXT_TOKEN_BEGIN


BEGIN_STATE(PCHVML_DATA_STATE)
    ADVANCE_TO(PCHVML_DATA_STATE);
    RECONSUME_IN(PCHVML_DATA_STATE);
END_STATE()

BEGIN_STATE(PCHVML_RAWTEXT_STATE)
END_STATE()

BEGIN_STATE(PCHVML_PLAINTEXT_STATE)
END_STATE()

BEGIN_STATE(PCHVML_TAG_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_END_TAG_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_TAG_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RCDATA_LESS_THAN_SIGN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RCDATA_END_TAG_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RCDATA_END_TAG_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RAWTEXT_LESS_THAN_SIGN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RAWTEXT_END_TAG_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_RAWTEXT_END_TAG_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BEFORE_ATTRIBUTE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_ATTRIBUTE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_ATTRIBUTE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BEFORE_ATTRIBUTE_VALUE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_ATTRIBUTE_VALUE_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_ATTRIBUTE_VALUE_SINGLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_ATTRIBUTE_VALUE_UNQUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_ATTRIBUTE_VALUE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_SELF_CLOSING_START_TAG_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BOGUS_COMMENT_STATE)
END_STATE()

BEGIN_STATE(PCHVML_MARKUP_DECLARATION_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_START_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_START_DASH_STATE)
        ADVANCE_TO(PCHVML_COMMENT_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_LESS_THAN_SIGN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_LESS_THAN_SIGN_BANG_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_LESS_THAN_SIGN_BANG_DASH_STATE)
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH_STATE)
        RECONSUME_IN(PCHVML_COMMENT_END_STATE);
    RECONSUME_IN(PCHVML_COMMENT_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_END_DASH_STATE)
        ADVANCE_TO(PCHVML_COMMENT_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_END_STATE)
        ADVANCE_TO(PCHVML_COMMENT_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_COMMENT_END_BANG_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BEFORE_DOCTYPE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_DOCTYPE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_DOCTYPE_PUBLIC_KEYWORD_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BEFORE_DOCTYPE_PUBLIC_ID_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_PUBLIC_ID_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_PUBLIC_ID_SINGLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_DOCTYPE_PUBLIC_ID_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BETWEEN_DOCTYPE_PUBLIC_ID_AND_SYSTEM_INFO_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_DOCTYPE_SYSTEM_KEYWORD_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BEFORE_DOCTYPE_SYSTEM_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_SYSTEM_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DOCTYPE_SYSTEM_SINGLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AFTER_DOCTYPE_SYSTEM_STATE)
END_STATE()

BEGIN_STATE(PCHVML_BOGUS_DOCTYPE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_CDATA_SECTION_STATE)
END_STATE()

BEGIN_STATE(PCHVML_CDATA_SECTION_BRACKET_STATE)
        ADVANCE_TO(PCHVML_CDATA_SECTION_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_CDATA_SECTION_END_STATE)
        ADVANCE_TO(PCHVML_CDATA_SECTION_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_CHARACTER_REFERENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_NAMED_CHARACTER_REFERENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_AMBIGUOUS_AMPERSAND_STATE)
END_STATE()

BEGIN_STATE(PCHVML_NUMERIC_CHARACTER_REFERENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_HEXADECIMAL_CHARACTER_REFERENCE_START_STATE)
END_STATE()

BEGIN_STATE(PCHVML_DECIMAL_CHARACTER_REFERENCE_START_STATE)
END_STATE()

BEGIN_STATE(PCHVML_HEXADECIMAL_CHARACTER_REFERENCE_STATE)
        ADVANCE_TO(PCHVML_NUMERIC_CHARACTER_REFERENCE_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_DECIMAL_CHARACTER_REFERENCE_STATE)
        ADVANCE_TO(PCHVML_NUMERIC_CHARACTER_REFERENCE_END_STATE);
END_STATE()

BEGIN_STATE(PCHVML_NUMERIC_CHARACTER_REFERENCE_END_STATE)
END_STATE()

BEGIN_STATE(PCHVML_SPECIAL_ATTRIBUTE_OPERATOR_IN_ATTRIBUTE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_SPECIAL_ATTRIBUTE_OPERATOR_AFTER_ATTRIBUTE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_DATA_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_FINISHED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_CONTROL_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_LEFT_BRACE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_RIGHT_BRACE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_LEFT_BRACKET_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_RIGHT_BRACKET_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_LEFT_PARENTHESIS_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_RIGHT_PARENTHESIS_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_DOLLAR_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_VALUE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_BEFORE_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_NAME_UNQUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_NAME_SINGLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_NAME_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_SINGLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_VALUE_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_TWO_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_THREE_DOUBLE_QUOTED_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_KEYWORD_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_KEYWORD_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_BYTE_SEQUENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_BYTE_SEQUENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_HEX_BYTE_SEQUENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_BINARY_BYTE_SEQUENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_BASE64_BYTE_SEQUENCE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_VALUE_NUMBER_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_INTEGER_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_FRACTION_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_EXPONENT_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_EXPONENT_INTEGER_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_SUFFIX_INTEGER_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NUMBER_INFINITY_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_VALUE_NAN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_STRING_ESCAPE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_STRING_ESCAPE_FOUR_HEXADECIMAL_DIGITS_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_JSONEE_VARIABLE_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_JSONEE_FULL_STOP_SIGN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_JSONEE_KEYWORD_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_JSONEE_STRING_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_AFTER_JSONEE_STRING_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_TEMPLATE_DATA_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_TEMPLATE_DATA_LESS_THAN_SIGN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_TEMPLATE_DATA_END_TAG_OPEN_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_TEMPLATE_DATA_END_TAG_NAME_STATE)
END_STATE()

BEGIN_STATE(PCHVML_EJSON_TEMPLATE_FINISHED_STATE)
END_STATE()

PCHVML_NEXT_TOKEN_END

#endif


